### PR TITLE
Deprecate lots of functions and message arguments

### PR DESCRIPTION
**Pull request by wlsf82**
This is a breaking change!

Tests and documentation were updated accordingly.

Versions on package.json and package-lock.json were also updated.

And some dependencies' versions were updated on package-lock.

Finally, this PR closes https://github.com/wlsf82/protractor-helper/issues/26.

## Pull Request Checklist

    - [x] Have you followed the steps in our [Contributing](https://github.com/wlsf82/protractor-helper/blob/master/docs/CONTRIBUTING.md) document?
    - [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wlsf82/protractor-helper/pulls) for the same update/change?
    - [x] Have you successfully ran tests with your changes locally?
    - [x] Have you written new tests for your changes, if necessary? I have deleted some tests ;)
    - [x] Have you added an explanation of what your changes do and why you'd like us to include them?
    - [x] Have you made improvements to the documentation, if necessary? ([docs/](https://github.com/wlsf82/protractor-helper/tree/master/docs) folder and [README.md](https://github.com/wlsf82/protractor-helper/blob/master/README.md))
    - [x] Have you linked the correct [GitHub issue](https://github.com/wlsf82/protractor-helper/issues), if there is any?

    > Pull requests that do not pass the automated tests on [SemaphoreCI](http://semaphoreci.com) and the code quality verification on [Better Code Hub](https://bettercodehub.com/) will not be reviewed

### CODE REVIEW

**Comment by wlsf82** [comment]
@PauloGoncalvesBH, can you review this PR so that we can launch v.4?

Please, leave the rebase and merge to me.

**Comment by wlsf82** [comment]
I also forgot to update some parts of the docs, with regards to the message argument.

**Comment by PauloGoncalvesBH** [comment]
I saw now, missed that > _Deprecations on version 4.0.0_

**Comment by wlsf82** [comment]
Done.

**Pull request merged**
