### PR TITLE
Add TypeScript definition file

### PR DESCRIPTION
**Pull request by wlsf82**
## Pull Request Checklist

This MR adds a TS definition file for the public functions of the protractor-helper library to help users on understanding which arguments the methods can receive, which types each argument should have, which arguments are mandatory and optional, and which types are returned by each method.

Closes https://github.com/wlsf82/protractor-helper/issues/67.

- [x] Have you followed the steps in our [Contributing](https://github.com/wlsf82/protractor-helper/blob/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wlsf82/protractor-helper/pulls) for the same update/change?
- [x] Have you successfully ran tests with your changes locally?
- [-] Have you written new tests for your changes, if necessary?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [-] Have you made improvements to the documentation, if necessary? ([docs/](https://github.com/wlsf82/protractor-helper/tree/master/docs) folder and [README.md](https://github.com/wlsf82/protractor-helper/blob/master/README.md))
- [x] Have you linked the correct [GitHub issue](https://github.com/wlsf82/protractor-helper/issues), if there is any?

> Pull requests that do not pass the coding static analysis and the automated tests on [Github Actions](https://github.com/wlsf82/protractor-helper/actions), and the code quality verification on [Better Code Hub](https://bettercodehub.com/) will not be reviewed.

### CODE REVIEW

**Comment by wlsf82** [comment]
Hi, @PauloGoncalvesBH, would you mind having a first look at this PR, please?

**Comment by wlsf82** [comment]
> Looks great to me.

Would you mind approving the PR, please?

**Comment by wlsf82** [comment]
> I liked the implementation.
> You just need to unify the [f9c2d9a](https://github.com/wlsf82/protractor-helper/commit/f9c2d9ae649a771f3bd08b6a8aca834cd9b72835) and [cd2207d](https://github.com/wlsf82/protractor-helper/commit/cd2207d259e06debef20278630e7fd0d1f0f5df3) commits and adjust your user.

@PauloGoncalvesBH, I have unified the commits as suggested, but what do you mean with adjusting my user?

**Comment by PauloGoncalvesBH** [comment]
> @PauloGoncalvesBH, I have unified the commits as suggested, but what do you mean with adjusting my user?

@wlsf82  It was just to adjust the name and email of the commit user. But I don't think it's critical enough to block this PR. So I will approve, adjust only if necessary.

image

**Comment by wlsf82** [comment]
@PauloGoncalvesBH, I have just pushed one more commit, which was actually missing (see https://github.com/wlsf82/protractor-helper/pull/68/commits/d571a868623173bba4aec65dbb8a6dfd64f514b1.)

I tested it locally in a sample project using npm link, and now, when typing a protractor-helper's method name, its signature is displayed to the user. :tada:

Sorry to ask you again, but could you do a final review and approve it again if you think it is ok, please?

**Comment by PauloGoncalvesBH** [comment]
Nice job 🥳

**Pull request merged**
